version: "3.8"

services:
  redis:
    image: redis:7.0.7
    volumes:
      - redis-data:/data
    ports:
      - '127.0.0.1:6379:6379'
    networks:
      - main

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - REDIS_HOSTS=redis:redis:6379
    networks:
      - main

volumes:
  redis-data:

networks:
  main:
